
# env: 
#   APP_VERSION: 1.0.0


# Build:
#   needs: test-unit
#   runs-on: ubuntu-latest
#   steps:
#     - name: repo 
#       uses: actions/checkout@v3
#     - name: install QEMU
#       uses: docker/setup-qemu-action@v1
#     - name: instalation docker build X
#       uses: docker/setup-buildx-action@v1
#     - name: docker hub auth 
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secret.LOGIN }}
#         password: ${{ secret.PASSWORD }}

#     - name: Build & push 
#       uses: docker/build-pushaction@v2 
#       with:
#         context: . 
#         push: true 
#         tags: ${{ secret.LOGIN }}/contianer-nodejs:$APP_VERSION