# This is a basic workflow to help you get started with Actions

name: artefact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
    - name: recuperation du repo 
      uses: actions/checkout@v3
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: install
      run: npm install
    - name: starting project 
      run: npm run start
    - name: cover test 
      run: npm run cover 


    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /Users/vanoud/Documents/DEV/exo-git/artifact/quick-example-of-testing-in-nodejs/reports/awesome-reports/mochawesome.html
